### ISSUE TITLE
Typo in vault password file parameter

### ISSUE THREAD

**Issue by bbaassssiiee** [Duffney/becomeansible#11]
https://github.com/Duffney/becomeansible/blob/54de10742a97937099a1feaf1555d02b0501fdda/chapter-10/ansible-action/entrypoint.sh#L5

**Comment by duffney** [comment]
Hey @bbaassssiiee,

I appreciate you taking the time to point that out. I've corrected the typo.

https://github.com/Duffney/becomeansible/commit/cae4fa0bfa322c8aba0168eff8d2b0293cf96447

Thanks!
