### ISSUE TITLE
chapter-03/aws/aws_create_windows_ec_instance.yaml  - ami id expired

### ISSUE THREAD

**Issue by bramdokman** [Duffney/becomeansible#19]
As of now line 76 => image: ami-0f5761c546ea1265a

**Comment by duffney** [comment]
Hey @bramdokman,

I greatly appreciate you taking the time to file the issue. I'll get it updated shortly.

Thanks!

**Comment by duffney** [comment]
I've updated the windows ami, thank you again. :)
